#!/bin/bash

: ${ENV_TEST_CASE:=0}

if [ $ENV_TEST_CASE -eq 1 ]; then
    unset CABOT_REALSENSE_SERIAL_1
    unset CABOT_REALSENSE_SERIAL_2
    unset CABOT_REALSENSE_SERIAL_3
    unset CABOT_CAMERA_NAME_1
    unset CABOT_CAMERA_NAME_2
    unset CABOT_CAMERA_NAME_3
fi

if [ $ENV_TEST_CASE -eq 2 ]; then
    export CABOT_REALSENSE_SERIAL_1=141322250657
    export CABOT_REALSENSE_SERIAL_2=819112073120
    export CABOT_REALSENSE_SERIAL_3=933322072143
    export CABOT_CAMERA_NAME_1=rs1
    export CABOT_CAMERA_NAME_2=rs2
    export CABOT_CAMERA_NAME_3=rs3
fi
